### ISSUE TITLE
Missing dependency Webrick in Gemfile for Ruby 3.0.0

### ISSUE THREAD

**Issue by josueadelima** [tomrutgers/middleman-webpack#169]
Hello,

As mentioned here https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/:

> The following libraries are no longer bundled gems or standard libraries. Install the corresponding gems to use these
> - features.
> - sdbm
> - webrick
> - net-telnet
> - xmlrpc

We need to add this:

```ruby
gem "webrick", "~> 1.7"
```
to the Gemfile, so Middleman can work with Ruby 3.0.0

NOTE: It looks like middleman team added Webbrick as dependency on the last version. (https://github.com/middleman/middleman/issues/2422), maybe just update the middleman version?

Thanks!

**Comment by tomrutgers** [comment]
4.3.11 is already being used, as stated in `gemfile.lock`
